-- ========================================================
-- ENCOCNS Supabase Database Schema & Initial Data
-- Supabase 대시보드 -> SQL Editor 에서 아래 전체 코드를 복사하여 Run 실행하세요.
-- ========================================================

-- 1. 프로젝트 (Projects) 테이블
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period TEXT NOT NULL,
    title TEXT NOT NULL,
    client TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. 뉴스 및 보도자료 (News) 테이블
CREATE TABLE IF NOT EXISTS public.news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS image_url TEXT;

-- 3. 채용 공고 (Careers) 테이블
CREATE TABLE IF NOT EXISTS public.careers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT NOT NULL,
    badge TEXT NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. 고객 문의 내역 (Inquiries) 테이블
CREATE TABLE IF NOT EXISTS public.inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    company TEXT,
    content TEXT NOT NULL,
    status TEXT DEFAULT '접수완료' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. 어드민 사용자 (Admin Users) 테이블
CREATE TABLE IF NOT EXISTS public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT DEFAULT 'admin' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS (Row Level Security) 설정 및 공개 읽기 허용
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.careers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- 익명 사용자 읽기/쓰기 권한 정책 (개발/학습용)
CREATE POLICY "Allow public read projects" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update/delete projects" ON public.projects FOR ALL USING (true);

CREATE POLICY "Allow public read news" ON public.news FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update/delete news" ON public.news FOR ALL USING (true);

CREATE POLICY "Allow public read careers" ON public.careers FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update/delete careers" ON public.careers FOR ALL USING (true);

CREATE POLICY "Allow public insert inquiries" ON public.inquiries FOR ALL USING (true);

CREATE POLICY "Allow public read admin_users" ON public.admin_users FOR ALL USING (true);

-- ========================================================
-- 초기 데이터 주입 (Initial Seed Data)
-- ========================================================

-- 어드민 계정 데이터
INSERT INTO public.admin_users (username, password, name, role)
VALUES ('encocns2011', '12345678', '슈퍼관리자', 'admin')
ON CONFLICT (username) DO NOTHING;

-- 프로젝트 초기 데이터
INSERT INTO public.projects (period, title, client, description) VALUES
('2019.05 ~ 현재', 'IFRS 시스템 구축', 'LINE Financial Plus', 'IFRS 대손충당금, 금융상품평가(CF엔진), ENCO FrameWork 도입'),
('2018.01 ~ 현재', 'IFRS 시스템 유지보수', '한국증권금융', 'IFRS 시스템 유지보수'),
('2013.02 ~ 현재', 'CMBS 유지보수', 'KB국민은행', '유가증권 유지보수 사업 참여'),
('2018.08 ~ 2019.04', '내부회계시스템 고도화', '카카오뱅크', '내부회계시스템 고도화 개발, ENCO FrameWork 도입'),
('2018.07 ~ 2019.10', '농협카드 차세대', 'NH농협카드', '계정계/승인계 개발 참여'),
('2018.05 ~ 2019.03', '업적평가용 ECL 시스템 구축', 'NH농협은행', '업적평가용 ECL 시스템 구축 사업 참여');

-- 뉴스 초기 데이터
INSERT INTO public.news (date, title, content) VALUES
('2024.03.15', 'ENCO CNS, 차세대 금융 IFRS9 솔루션 고도화 완료', 'ENCO CNS가 대용량 금융 데이터 처리를 위한 차세대 IFRS9 솔루션 고도화 작업을 성공적으로 완료했습니다.'),
('2024.01.10', '2024년도 신입 및 경력 사원 정기 채용 실시', '금융 IT 혁신을 함께 이끌어갈 우수한 인재를 모십니다.');

-- 채용 공고 초기 데이터
INSERT INTO public.careers (date, badge, title, content) VALUES
('2024.03.01 ~ 상시채용', 'D-DAY', '금융 IT 시스템 Java/Spring 개발자 모집', '금융권 차세대 및 IFRS9 시스템 개발을 담당할 열정적인 개발자를 모십니다.'),
('2024.02.15 ~ 상시채용', '채용중', '금융 데이터 분석 및 데이터베이스 엔지니어', '대용량 데이터 아키텍처 설계 및 데이터베이스 최적화 담당자 채용');
